theme: jekyll-theme-tactile
base: https://impresso.github.io
lang: en
languages: ["en", "fr", "de"]

collections:
  agenda:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  partners:
    output: true
    permalink: /:collection/:path/
  glossary:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "agenda"
    values:
      layout: "agenda"
  - scope:
      path: ""
      type: "glossary"
    values:
      layout: "glossary"